### ISSUE TITLE
Git hub loves Teams or Does it?

### ISSUE THREAD

**Issue by nhsbandit** [TauntonandSomersetNHSTrust/OpenEHR#1]
What happens when i do this?

**Comment by nhshaydn** [comment]
Uh oh...

**Comment by nhsbandit** [comment]
Update

**Comment by nhsbandit** [comment]
what about now

**Comment by nhsbandit** [comment]
why has this not been fixed yet!!!!!

**Comment by nhshaydn** [comment]
@nhsbandit Looks like I don't have write access to the repo in order for me to branch it, create a pull request, link this issue to the request, then close the the issue

**Comment by nhsbandit** [comment]
Try now, i have change the org base permissions

**Comment by nhshaydn** [comment]
Closing with pull request linked
